export default {
    PROFILE_FORWARD:'chevron-forward-outline',
    BACK_ARROW: 'arrow-back-outline',
    NAVIGATE: 'navigate',
    PERSON: 'person-outline',
    LOCATION:'location-outline',
    CARD: 'card-outline',
    BASKET: 'basket-outline',
    HEART: 'heart-outline',
    PERSON_ADD: 'person-add-outline',
    LOCK:'lock-closed-outline',
    HELP: 'help-circle-outline',
    LOG_OUT: 'log-out-outline',
    SEARCH: 'search-outline',
    DOWN_ARROW: 'chevron-down-outline',
    NOTIFICATION: 'notifications-outline',
    CART:'cart-outline',
    OPTIONS:'options-outline',
    ADD:'add-circle-outline',
    SUB:'remove-circle-outline',
    DELIVERY: 'subway-outline',
    HEART_FILLED: 'heart',
    MENU: 'menu-outline',
    ADD: 'add-outline',
    RIGHT:'arrow-forward-outline',
    TRASH: 'trash-outline',
}